// frontend/src/components/dashboard/LocalAddonContextMenu.tsx
import { Addon, LocalAddonService } from '@/lib/wails'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from '@/components/ui/context-menu'
import {
  AlertTriangleIcon,
  BugIcon,
  CheckIcon,
  FolderOpen,
  GithubIcon,
  Trash2Icon,
} from 'lucide-react'
import { safeCall } from '@/lib/utils.ts'
import type { ReactNode } from 'react'
import { Browser } from '@wailsio/runtime'
import { toast } from '@/components/ui/toast.tsx'
import { useAddonStore } from '@/stores/addonStore.ts'

interface LocalAddonContextMenuProps {
  addon: Addon
  children: ReactNode
  onOpenChange: (open: boolean) => void
}

export const LocalAddonContextMenu = ({
  addon,
  children,
  onOpenChange,
}: LocalAddonContextMenuProps) => {
  const { uninstall, unmanage } = useAddonStore()

  const openDirectory = async () => {
    const [, err] = await safeCall(LocalAddonService.OpenDirectory(addon.name))
    if (err) {
      console.error('Failed to open directory:', err)
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to open directory for addon "${addon.alias}".`,
      })
    }
  }

  const handleAddonAction = async (action: 'uninstall' | 'unmanage') => {
    const actionPast = action === 'uninstall' ? 'Uninstalled' : 'Unmanaged'

    const [result, err] = await safeCall(
      action === 'uninstall' ? uninstall(addon) : unmanage(addon)
    )

    if (err) {
      console.error(`[LocalAddonContextMenu] Failed to ${action} addon:`, err)
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to ${action} addon "${addon.alias}".`,
      })

      return
    }

    if (result) {
      toast({
        icon: CheckIcon,
        title: actionPast,
        description: `Addon "${addon.alias}" has been ${actionPast.toLowerCase()}.`,
      })
    } else {
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to ${action} addon "${addon.alias}".`,
      })
    }
  }

  return (
    <ContextMenu onOpenChange={onOpenChange}>
      <ContextMenuTrigger>{children}</ContextMenuTrigger>
      <ContextMenuContent>
        <ContextMenuItem onClick={openDirectory}>
          <FolderOpen size={16} />
          Open directory
        </ContextMenuItem>
        {addon.isManaged && (
          <>
            <ContextMenuItem onClick={() => Browser.OpenURL(`https://github.com/${addon.repo}`)}>
              <GithubIcon size={16} />
              <span>View code</span>
            </ContextMenuItem>

            <ContextMenuItem
              onClick={() => Browser.OpenURL(`https://github.com/${addon.repo}/issues/new`)}
            >
              <BugIcon size={16} />
              <span>Report issue</span>
            </ContextMenuItem>

            <ContextMenuItem variant="warning" onClick={() => handleAddonAction('unmanage')}>
              <AlertTriangleIcon size={16} />
              <span>Unmanage</span>
            </ContextMenuItem>
          </>
        )}
        <ContextMenuItem variant="destructive" onClick={() => handleAddonAction('uninstall')}>
          <Trash2Icon size={16} />
          Uninstall
        </ContextMenuItem>
      </ContextMenuContent>
    </ContextMenu>
  )
}

// frontend/src/components/local_addon/LocalAddonContextMenu.svelte
<script lang="ts">
    import type {Snippet} from "svelte";
    import * as ContextMenu from "$lib/components/ui/context-menu/index.js";
    import Trash from "lucide-svelte/icons/trash";
    import AlertTriangle from "lucide-svelte/icons/alert-triangle";
    import Bug from "lucide-svelte/icons/bug";
    import Github from "lucide-svelte/icons/github";
    import FolderOpen from "lucide-svelte/icons/folder-open";
    import addons from "../../addons";
    import {LocalAddonService, type Addon} from "$lib/wails";
    import {toast} from "../../utils";
    import {Browser} from "@wailsio/runtime"

    let {
        contextTriggerArea,
        addon,
    }: {
        contextTriggerArea: Snippet;
        addon: Addon;
    } = $props();

    // Generic handler for addon operations
    async function handleAddonAction(action: 'uninstall' | 'unmanage') {
        const actionVerb = action === 'uninstall' ? 'Uninstalling' : 'Unmanaging';
        const actionPast = action === 'uninstall' ? 'Uninstalled' : 'Unmanaged';
        
        console.debug(`${actionVerb} addon: ${addon.name}`);
        const success = await addons[action](addon.name);
        
        if (success) {
            console.debug(`${actionPast} addon: ${addon.name}`);
            toast.success(`${addon.alias} was ${action}ed`);
        } else {
            console.error(`Failed to ${action} addon: ${addon.name}`);
            toast.error(`Failed to ${action} ${addon.alias}`);
        }
    }

    async function handleOpenDirectory() {
        try {
            await LocalAddonService.OpenDirectory(addon.name);
        } catch (e) {
            console.error("Failed to open directory: ", e);
            toast.error(`Failed to open directory: ${e}`);
        }
    }
</script>

<ContextMenu.Root>
    <ContextMenu.Trigger>
        {@render contextTriggerArea()}
    </ContextMenu.Trigger>
    <ContextMenu.Content>
        <ContextMenu.Item class="gap-2" onclick={handleOpenDirectory}>
            <FolderOpen size={16}/>
            Open directory
        </ContextMenu.Item>
        
        {#if addon.isManaged}
            <ContextMenu.Item class="gap-3" onclick={() => Browser.OpenURL(`https://github.com/${addon.repo}`)}>
                <Github size={16}/>
                View code
            </ContextMenu.Item>
            <ContextMenu.Item class="gap-2" onclick={() => Browser.OpenURL(`https://github.com/${addon.repo}/issues/new`)}>
                <Bug size={16}/>
                Report issue
            </ContextMenu.Item>
        {/if}

        <ContextMenu.Item class="gap-2" onclick={() => handleAddonAction('uninstall')}>
            <Trash size={16}/>
            Uninstall
        </ContextMenu.Item>

        {#if addon.isManaged}
            <ContextMenu.Item class="gap-2" onclick={() => handleAddonAction('unmanage')}>
                <AlertTriangle size={16}/>
                Unmanage
            </ContextMenu.Item>
        {/if}
    </ContextMenu.Content>
</ContextMenu.Root>
