// frontend/src/components/remote_addon/RemoteAddonReadme.svelte
<script lang="ts">
  import ImageOverlay from './ImageOverlay.svelte'

  let {readme}: { readme: string } = $props()

  let selectedImage: { src: string, alt: string } | null = $state(null)
  let isImageOverlayOpen: boolean = $state(false)

  function handleImageClick(event: MouseEvent) {
    const target = event.target as HTMLElement
    if (target.tagName === 'IMG') {
      const img = target as HTMLImageElement
      selectedImage = {
        src: img.src,
        alt: img.alt || 'Image'
      }
      isImageOverlayOpen = true
    }
  }

  function handleOverlayClose() {
    isImageOverlayOpen = false
    // Clear the selected image after the overlay is closed
    setTimeout(() => {
      selectedImage = null
    }, 200) // Wait for the animation to finish
  }
</script>

<style>
    /* Make links more noticable */
    #markdown-container :global(a) {
        @apply
        text-blue-400 hover:text-blue-500
        hover:underline
        transition-all
        ;
    }

    /* All headers need a border and some padding */
    #markdown-container :global(h1),
    #markdown-container :global(h2),
    #markdown-container :global(h3),
    #markdown-container :global(h4),
    #markdown-container :global(h5),
    #markdown-container :global(h6) {
        @apply my-2 border-b border-gray-600 pb-2;
    }

    /* Headers need to be bigger and bold */
    #markdown-container :global(h1) {
        @apply text-3xl font-semibold;
    }

    #markdown-container :global(h2) {
        @apply text-2xl font-semibold;
    }

    #markdown-container :global(h3) {
        @apply text-xl font-semibold;
    }

    #markdown-container :global(h4) {
        @apply text-lg font-semibold;
    }

    #markdown-container :global(h5) {
        @apply text-base font-semibold;
    }

    #markdown-container :global(h6) {
        @apply text-sm font-bold;
    }

    /* Links containing images need margins */
    #markdown-container :global(a img) {
        @apply my-3;
    }

    /* Make images clickable */
    #markdown-container :global(img) {
        @apply
        cursor-pointer
        hover:opacity-90
        transition-all
        hover:scale-105
        ;
        transition-duration: 400ms;
    }

    /* Code blocks need to be more distinct */
    #markdown-container :global(code) {
        @apply
        bg-gray-700
        py-0.5
        px-1
        overflow-x-auto
        rounded-sm
        font-mono
        ;
    }

    /* Styling for pre blocks */
    #markdown-container :global(pre) {
        @apply
        bg-neutral-900 /* Slightly darker background */
        p-4           /* More padding */
        my-4          /* Vertical margin */
        overflow-x-auto
        rounded-md    /* More rounded corners */
        font-mono
        text-muted-foreground
        ;
    }

    /* Reset code styling when inside pre */
    #markdown-container :global(pre code) {
        @apply
        bg-transparent /* Remove background */
        p-0           /* Remove padding */
        rounded-none  /* Remove rounded corners */
        ;
    }

    /* Each paragraph needs some margin */
    #markdown-container :global(p) {
        @apply my-2;
    }

    /* UL and OL need some margin */
    #markdown-container :global(ul),
    #markdown-container :global(ol) {
        @apply my-5;
    }

    /* UL needs decorations */
    #markdown-container :global(ul) {
        @apply list-disc list-inside;
    }

    /* OL needs decorations */
    #markdown-container :global(ol) {
        @apply list-decimal list-inside;
    }
</style>

<div id="markdown-container" class="max-w-[95%] mx-auto" on:click={handleImageClick}>
  {@html readme}
</div>

{#if selectedImage}
  <ImageOverlay
    src={selectedImage.src}
    alt={selectedImage.alt}
    bind:open={isImageOverlayOpen}
    onClose={handleOverlayClose}
  />
{/if}

// frontend/src/components/shared/RemoteAddonReadme.tsx
import { useState, type ComponentProps } from 'react';
import {
  Dialog,
  DialogClose,
  DialogOverlay,
  DialogPrimitive
} from '@/components/ui/dialog'
import Markdown from 'react-markdown'
import { XIcon } from 'lucide-react';

interface Props {
  readme: string
}

export const RemoteAddonReadme = ({ readme }: Props) => {
  const [selectedImage, setSelectedImage] = useState<HTMLImageElement | null>(null);

  const components = {
      a: ({ node, ...props }: ComponentProps<"a"> & { node?: unknown }) => (
        <a
          className="text-blue-400 hover:text-blue-500 hover:underline transition-all"
          {...props}
        />
      ),
      h1: ({ node, ...props }: ComponentProps<"h1"> & { node?: unknown }) => (
        <h1
          className="my-2 border-b border-gray-600 pb-2 text-3xl font-semibold"
          {...props}
        />
      ),
      h2: ({ node, ...props }: ComponentProps<"h2"> & { node?: unknown }) => (
        <h2
          className="my-2 border-b border-gray-600 pb-2 text-2xl font-semibold"
          {...props}
        />
      ),
      h3: ({ node, ...props }: ComponentProps<"h3"> & { node?: unknown }) => (
        <h3
          className="my-2 border-b border-gray-600 pb-2 text-xl font-semibold"
          {...props}
        />
      ),
      h4: ({ node, ...props }: ComponentProps<"h4"> & { node?: unknown }) => (
        <h4
          className="my-2 border-b border-gray-600 pb-2 text-lg font-semibold"
          {...props}
        />
      ),
      h5: ({ node, ...props }: ComponentProps<"h5"> & { node?: unknown }) => (
        <h5
          className="my-2 border-b border-gray-600 pb-2 text-base font-semibold"
          {...props}
        />
      ),
      h6: ({ node, ...props }: ComponentProps<"h6"> & { node?: unknown }) => (
        <h6
          className="my-2 border-b border-gray-600 pb-2 text-sm font-bold"
          {...props}
        />
      ),
      img: ({ node, ...props }: ComponentProps<"img"> & { node?: unknown }) => (
        <img
        onClick={(event) => setSelectedImage(event.currentTarget)}
          className="my-3 cursor-pointer transition-all scale-[90%] hover:scale-[95%]"
          style={{ transitionDuration: "400ms" }}
          {...props}
        />
      ),
      code: ({
        node,
        inline,
        className,
        children,
        ...props
      }: ComponentProps<"code"> & { node?: unknown; inline?: boolean }) => {
        const match = /language-(\w+)/.exec(className || "");
        return !inline && match ? (
          <code className={className} {...props}>
            {children}
          </code>
        ) : (
          <code
            className="bg-muted py-0.5 px-1 overflow-x-auto rounded-sm font-mono"
            {...props}
          >
            {children}
          </code>
        );
      },
      pre: ({ node, ...props }: ComponentProps<"pre"> & { node?: unknown }) => (
        <pre
          className="bg-muted p-4 my-4 overflow-x-auto rounded-md font-mono text-muted-foreground"
          {...props}
        />
      ),
      p: ({ node, ...props }: ComponentProps<"p"> & { node?: unknown }) => (
        <p className="my-2" {...props} />
      ),
      ul: ({ node, ...props }: ComponentProps<"ul"> & { node?: unknown }) => (
        <ul className="my-5 list-disc list-inside" {...props} />
      ),
      ol: ({ node, ...props }: ComponentProps<"ol"> & { node?: unknown }) => (
        <ol className="my-5 list-decimal list-inside" {...props} />
      ),
    };

  return (
    <>
      {selectedImage && (
        <Dialog open={selectedImage !== null} onOpenChange={(open: boolean) => {
          if(!open) {
            setSelectedImage(null)
          }
        }}>
          <DialogOverlay className='fixed inset-0 z-50 bg-black/80'>
            <div className='content-wrapper z-50'>
              <DialogPrimitive.Content className='!p-0 !gap-0 !bg-transparent !border-0 !shadow-none !w-auto !h-auto'>
                  <div className='relative w-[95vw] h-[95vh] flex items-center justify-center'>
                    <div className='relative flex items-center justify-center min-w-[60vw] min-h-[60vh]'>
                      <div className='relative inline-block'>
                        <img 
                          src={selectedImage.src} 
                          alt={selectedImage.alt} 
                          className='rounded-lg max-w-[95vw] max-h-[95vh] w-auto h-auto object-contain' 
                        />
                        <DialogClose className='absolute -top-4 -right-4 rounded-full bg-background p-2 text-foreground hover:bg-muted transition-colors shadow-lg'>
                          <XIcon className='size-4' />
                          <span className='sr-only'>Close</span>
                        </DialogClose>
                      </div>
                    </div>
                  </div>
              </DialogPrimitive.Content>
            </div>
          </DialogOverlay>
        </Dialog>
      )}
      <Markdown components={components}>{readme}</Markdown>
    </>
  )
}
