// frontend/src/components/addon/LocalAddonContextMenu.svelte
<script lang="ts">
    import type {Snippet} from "svelte";
    import {addon as ad} from "../../../wailsjs/go/models";
    import * as ContextMenu from "$lib/components/ui/context-menu/index.js";
    import Trash from "lucide-svelte/icons/trash";
    import Bug from "lucide-svelte/icons/bug";
    import Github from "lucide-svelte/icons/github";
    import {toast} from "svelte-sonner";
    import addons from "../../addons";

    let {
        contextTriggerArea,
        addon,
    }: {
        contextTriggerArea: Snippet;
        addon: ad.Addon;
    } = $props();

    async function handleUninstall() {
        console.debug("Uninstalling addon: ", addon.name);
        let didUninstall = await addons.uninstall(addon.name);
        if (didUninstall) {
            console.debug("Uninstalled addon: ", addon.name);
            toast.success(`${addon.displayName} was uninstalled`);
        } else {
            console.error("Failed to uninstall addon: ", addon.name);
            toast.error(`Failed to uninstall ${addon.displayName}`);
        }
    }
</script>

<ContextMenu.Root>
    <ContextMenu.Trigger>
        {@render contextTriggerArea()}
    </ContextMenu.Trigger>
    <ContextMenu.Content>
        {#if addon.isManaged}
            <ContextMenu.Item
                    class="gap-3"
                    onclick={() => {
                    // @ts-ignore
                    window.runtime.BrowserOpenURL(
                        `https://github.com/${addon.repo}`,
                    );
                }}
            >
                <Github size={16}/>
                View code
            </ContextMenu.Item>
            <ContextMenu.Item
                    class="gap-2"
                    onclick={() => {
                    // @ts-ignore
                    window.runtime.BrowserOpenURL(
                        `https://github.com/${addon.repo}/issues/new`,
                    );
                }}
            >
                <Bug size={16}/>
                Report issue
            </ContextMenu.Item>
        {/if}

        <ContextMenu.Item class="gap-2" onclick={handleUninstall}>
            <Trash size={16}/>
            Uninstall
        </ContextMenu.Item>
    </ContextMenu.Content>
</ContextMenu.Root>

// frontend/src/components/dashboard/LocalAddonContextMenu.tsx
import { Addon, LocalAddonService } from '@/lib/wails'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from '@/components/ui/context-menu'
import {
  AlertTriangleIcon,
  BugIcon,
  CheckIcon,
  FolderOpen,
  GithubIcon,
  Trash2Icon,
} from 'lucide-react'
import { safeCall } from '@/lib/utils.ts'
import type { ReactNode } from 'react'
import { Browser } from '@wailsio/runtime'
import { toast } from '@/components/ui/toast.tsx'
import { useAddonStore } from '@/stores/addonStore.ts'

interface LocalAddonContextMenuProps {
  addon: Addon
  children: ReactNode
  onOpenChange: (open: boolean) => void
}

export const LocalAddonContextMenu = ({
  addon,
  children,
  onOpenChange,
}: LocalAddonContextMenuProps) => {
  const { uninstall, unmanage } = useAddonStore()

  const openDirectory = async () => {
    const [, err] = await safeCall(LocalAddonService.OpenDirectory(addon.name))
    if (err) {
      console.error('Failed to open directory:', err)
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to open directory for addon "${addon.alias}".`,
      })
    }
  }

  const handleAddonAction = async (action: 'uninstall' | 'unmanage') => {
    const actionPast = action === 'uninstall' ? 'Uninstalled' : 'Unmanaged'

    const [result, err] = await safeCall(
      action === 'uninstall' ? uninstall(addon) : unmanage(addon)
    )

    if (err) {
      console.error(`[LocalAddonContextMenu] Failed to ${action} addon:`, err)
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to ${action} addon "${addon.alias}".`,
      })

      return
    }

    if (result) {
      toast({
        icon: CheckIcon,
        title: actionPast,
        description: `Addon "${addon.alias}" has been ${actionPast.toLowerCase()}.`,
      })
    } else {
      toast({
        icon: AlertTriangleIcon,
        title: 'Error',
        description: `Failed to ${action} addon "${addon.alias}".`,
      })
    }
  }

  return (
    <ContextMenu onOpenChange={onOpenChange}>
      <ContextMenuTrigger>{children}</ContextMenuTrigger>
      <ContextMenuContent>
        <ContextMenuItem onClick={openDirectory}>
          <FolderOpen size={16} />
          Open directory
        </ContextMenuItem>
        {addon.isManaged && (
          <>
            <ContextMenuItem onClick={() => Browser.OpenURL(`https://github.com/${addon.repo}`)}>
              <GithubIcon size={16} />
              <span>View code</span>
            </ContextMenuItem>

            <ContextMenuItem
              onClick={() => Browser.OpenURL(`https://github.com/${addon.repo}/issues/new`)}
            >
              <BugIcon size={16} />
              <span>Report issue</span>
            </ContextMenuItem>

            <ContextMenuItem variant="warning" onClick={() => handleAddonAction('unmanage')}>
              <AlertTriangleIcon size={16} />
              <span>Unmanage</span>
            </ContextMenuItem>
          </>
        )}
        <ContextMenuItem variant="destructive" onClick={() => handleAddonAction('uninstall')}>
          <Trash2Icon size={16} />
          Uninstall
        </ContextMenuItem>
      </ContextMenuContent>
    </ContextMenu>
  )
}
