// frontend/src/components/local_addon/LocalAddonDialog.svelte
<script lang="ts">
  import DOMPurify from 'dompurify'
  import {
    ArrowUpCircle,
    Package,
    RefreshCcw,
    Tag,
    ThumbsDown as Dislike,
    ThumbsUp as Like,
    Trash2,
    User
  } from 'lucide-svelte'
  import {marked} from 'marked'

  import addons from '@/addons'
  import {apiClient} from '@/api'
  import {safeCall, toast} from '@/utils'
  import {addonDialog} from '$atoms/local-addon.svelte'
  import {isAuthenticated} from '$atoms/user.svelte'
  import {Badge} from '$lib/components/ui/badge/index'
  import {Button} from '$lib/components/ui/button/index'
  import * as Dialog from '$lib/components/ui/dialog/index'
  import type {Addon} from '$lib/wails'
  import {AddonManifest} from '$lib/wails'

  import RemoteAddonReadme from '../remote_addon/RemoteAddonReadme.svelte'

  let addon: Addon | null = $derived(addonDialog.addon)
  let open = $derived(addonDialog.isOpen)
  let uninstallClicks = $state(0)
  let uninstallTimeout: any
  let rating = $state(0)
  let readme = $state('Loading description...')

  marked.setOptions({
    gfm: true,
    breaks: true,
  })

  $effect(() => {
    if (addon && open) {
      getMyRating()
      getReadme()
    } else {
      rating = 0
      readme = 'Loading description...'
    }
  })

  async function getReadme() {
    if (!addon) return
    try {
      if (!addon.repo) {
        const fallbackReadme = addon.description || 'No description provided.'
        readme = DOMPurify.sanitize(marked.parse(fallbackReadme, {async: false}))
        return
      }

      // Default to 'main' branch if not specified
      const branch = 'main'
      const response = await fetch(
        `https://raw.githubusercontent.com/${addon.repo}/${branch}/README.md`,
      )
      if (!response.ok) {
        const fallbackReadme = addon.description || 'No description provided.'
        readme = DOMPurify.sanitize(marked.parse(fallbackReadme, {async: false}))
        return
      }
      const rawReadme = await response.text()
      readme = DOMPurify.sanitize(await marked.parse(rawReadme))
    } catch (e) {
      console.error('Error fetching README:', e)
      const errorReadme = addon.description || 'Error loading description.'
      readme = DOMPurify.sanitize(marked.parse(errorReadme, {async: false}))
    }
  }

  async function handleMatchAddon() {
    if (!addon) return
    const [manifest, manifestError] = await safeCall<AddonManifest>(() => addons.getManifest(addon.name))
    if (manifestError || !manifest) {
      console.error('Failed to get manifest:', manifestError)
      toast.error(`Failed to get manifest: ${manifestError || 'Unknown error'}`)
      return
    }

    const [installError] = await safeCall<boolean>(() => addons.install(manifest, 'latest'))
    if (installError) {
      const errorString = String(installError)
      if (errorString.includes('no release found')) {
        toast.error('No release found for this addon.')
      } else {
        console.error('Failed to install addon during match:', installError)
        toast.error(`Failed to match addon: ${errorString.substring(0, 100)}`)
      }
      return
    }

    toast.success('Addon matched',
      {
        description: `${addon.alias} was matched and will be managed by Classic Addon Manager`,
        duration: 7000
      }
    )
    addonDialog.setOpen(false)
  }

  async function handleUninstall() {
    if (!addon) return
    if (uninstallClicks === 0) {
      toast.info('Click again to uninstall', {dismissable: true})
    }
    uninstallClicks++

    uninstallTimeout = setTimeout(() => {
      uninstallClicks = 0
    }, 5000)

    if (uninstallClicks === 2) {
      clearTimeout(uninstallTimeout)
      uninstallClicks = 0
      console.debug('Uninstalling addon: ', addon.name)
      let didUninstall = await addons.uninstall(addon.name)
      if (didUninstall) {
        console.debug('Uninstalled addon: ', addon.name)
        toast.success(`${addon.alias} was uninstalled`)
      } else {
        console.error('Failed to uninstall addon: ', addon.name)
        toast.error(`Failed to uninstall ${addon.alias}`)
      }
    }
  }

  async function handleReinstall() {
    if (!addon) return
    const [manifest, manifestError] = await safeCall<AddonManifest>(() => addons.getManifest(addon.name))

    if (manifestError || !manifest) {
      if (manifestError.toString().includes('no release found')) {
        toast.error('No release found for this addon')
      } else {
        toast.error('Failed to reinstall addon')
      }
      return
    }

    let didInstall: boolean = await addons.install(manifest, 'latest')
    if (!didInstall) return
    toast.success('Addon reinstalled',
      {description: `${addon.alias} was reinstalled`, duration: 7000}
    )
    addonDialog.setOpen(false)
  }

  function getMyRating() {
    if (!addon || !open || !isAuthenticated()) return
    apiClient.get(`/addon/${addon.name}/my-rating`).then(async rateResponse => {
      if (rateResponse.status === 200) {
        const r = await rateResponse.json()
        rating = r.data.rating
      }
    }).catch(e => {
      console.error('Failed to fetch rating', e)
    })
  }

  async function handleRating(r: number) {
    if (!addon) return
    if (rating === r || r === 0) {
      return
    }
    const response = await apiClient.post(`/addon/${addon.name}/rate`, {
      is_like: r === 1
    })

    if (response.status !== 200) {
      toast.error('Could not rate addon, try again later')
      return
    }

    rating = r

    if (r === 1) {
      toast.success('Addon rated', {description: `Liked ${addon.alias}`})
    } else {
      toast.success('Addon rated', {description: `Disliked ${addon.alias}`})
    }
  }
</script>

{#if addon}
  <Dialog.Root {open} onOpenChange={addonDialog.setOpen}>
    <Dialog.Content class="sm:max-w-[600px] max-h-[90svh] flex flex-col p-0">
      <Dialog.Header class="p-6 pb-4 shrink-0 border-b">
        <Dialog.Title class="text-2xl font-semibold mb-1">{addon?.alias}</Dialog.Title>
        <div class="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm mb-3 text-muted-foreground">
          <span class="inline-flex items-center gap-1">
            <User class="w-3.5 h-3.5"/>
            <span class="font-normal text-foreground/90">{addon?.author}</span>
          </span>
          {#if addon?.version}
            <Badge variant="secondary" class="inline-flex items-center gap-1">
              <Tag class="w-3 h-3"/>
              {addon.version}
            </Badge>
          {:else}
            <Badge variant="outline">No Version</Badge>
          {/if}
        </div>
        {#if addon?.description}
          <Dialog.Description class="text-sm text-muted-foreground">{addon?.description}</Dialog.Description>
        {/if}
      </Dialog.Header>

      <div class="flex-1 overflow-y-auto p-6">
        {#if readme === 'Loading description...'}
          <div class="flex flex-col items-center justify-center h-full text-center text-muted-foreground pt-10">
            <Package class="w-12 h-12 mb-4 opacity-50"/>
            <p class="font-medium">Loading description...</p>
          </div>
        {:else}
          <RemoteAddonReadme {readme}/>
        {/if}

        {#if !addon?.isManaged}
          <div class="border rounded-lg p-4 bg-card mt-6">
            <div class="space-y-3">
              <div class="flex items-center gap-2 text-muted-foreground">
                <Package class="w-4 h-4"/>
                <p class="text-sm font-medium">This addon is not managed by Classic Addon Manager</p>
              </div>

              {#await addons.repoHasAddon(addon?.name)}
                <div class="flex items-center gap-2 text-sm text-muted-foreground">
                  <div class="w-3 h-3 rounded-full border-2 border-t-transparent border-current animate-spin"></div>
                  <span>Checking repository...</span>
                </div>
              {:then found}
                {#if found}
                  <div class="space-y-3">
                    <p class="text-sm text-muted-foreground">Good news! This addon was found in our
                      repository. Would you like Classic Addon Manager to handle updates for
                      you?</p>
                    <Button class="w-full sm:w-auto" onclick={handleMatchAddon}>
                      <ArrowUpCircle class="w-4 h-4 mr-2"/>
                      Yes, manage this addon
                    </Button>
                  </div>
                {/if}
              {/await}
            </div>
          </div>
        {/if}
      </div>

      <Dialog.Footer class="p-4 border-t">
        <div class="flex justify-between items-center w-full gap-4">
          {#if addon?.isManaged}
            <div class="flex gap-1 items-center">
              {#if isAuthenticated()}
                <Button
                  variant="ghost"
                  size="icon"
                  class="h-8 w-9 transition-all duration-200 hover:scale-105 hover:bg-blue-100 dark:hover:bg-blue-900/30 {rating === 1 ? 'bg-blue-100 dark:bg-blue-900/30 border border-blue-500' : ''}"
                  onclick={() => handleRating(1)}
                  aria-label="Like addon"
                >
                  <Like class="w-5 h-5 {rating === 1 ? 'text-blue-500' : 'text-muted-foreground group-hover:text-blue-500'}"/>
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  class="h-8 w-9 transition-all duration-200 hover:scale-105 hover:bg-red-100 dark:hover:bg-red-900/30 {rating === -1 ? 'bg-red-100 dark:bg-red-900/30 border border-red-500' : ''}"
                  onclick={() => handleRating(-1)}
                  aria-label="Dislike addon"
                >
                  <Dislike
                    class="w-5 h-5 {rating === -1 ? 'text-red-500' : 'text-muted-foreground group-hover:text-red-500'}"/>
                </Button>
              {:else}
                <span class="flex items-center gap-1 p-2 cursor-not-allowed opacity-50"
                  aria-label="Log in to rate addons">
                  <Like class="w-5 h-5 text-muted-foreground"/>
                  <Dislike class="w-5 h-5 text-muted-foreground"/>
                </span>
              {/if}
            </div>

            <div class="flex flex-col-reverse sm:flex-row sm:justify-end gap-2">
              <Button
                type="button"
                variant="outline"
                onclick={handleReinstall}
              >
                <RefreshCcw class="w-4 h-4 mr-2"/>
                Reinstall
              </Button>
              <Button
                type="button"
                variant="destructive"
                onclick={handleUninstall}
              >
                <Trash2 class="w-4 h-4 mr-2"/>
                {uninstallClicks === 1 ? 'Click to confirm' : 'Uninstall'}
              </Button>
            </div>
          {/if}
        </div>
      </Dialog.Footer>
    </Dialog.Content>
  </Dialog.Root>
{/if}

// frontend/src/components/dashboard/LocalAddonDialog.tsx
import { clsx } from 'clsx'
import { useAtom } from 'jotai'
import {
  AlertTriangleIcon,
  CheckIcon,
  PackageIcon,
  RefreshCw,
  Tag,
  ThumbsDownIcon,
  ThumbsUpIcon,
  Trash2,
  User,
} from 'lucide-react'
import { Suspense, useCallback, useEffect, useState } from 'react'

import { AddonRepositoryMatch } from '@/components/dashboard/AddonRepositoryMatch'
import { isAddonDialogOpenAtom, selectedAddonAtom } from '@/components/dashboard/atoms.ts'
import { RemoteAddonReadme } from '@/components/shared/RemoteAddonReadme'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { toast } from '@/components/ui/toast.tsx'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { apiClient } from '@/lib/api'
import { repoGetManifest } from '@/lib/repo'
import { safeCall } from '@/lib/utils'
import type { Addon, AddonManifest } from '@/lib/wails'
import { useAddonStore } from '@/stores/addonStore'
import { useUserStore } from '@/stores/userStore'

interface LocalAddonDialogProps {
  addon: Addon
  onOpenChange: (open: boolean) => void
  open: boolean
}

export const LocalAddonDialog = ({ addon, onOpenChange, open }: LocalAddonDialogProps) => {
  const [readme, setReadme] = useState<string>('loading')
  const [initiallyManaged, setInitiallyManaged] = useState(false)
  const [hasBeenOpened, setHasBeenOpened] = useState(false)
  const [rating, setRating] = useState(0)
  const [, setSelectedAddon] = useAtom(selectedAddonAtom)
  const [, setIsDialogOpen] = useAtom(isAddonDialogOpenAtom)
  const { isAuthenticated } = useUserStore()
  const { install, uninstall } = useAddonStore()

  // Set initial managed state when dialog opens
  useEffect(() => {
    if (open && !hasBeenOpened) {
      // Mark that we've opened the dialog and captured the initial state
      setHasBeenOpened(true)
      setInitiallyManaged(addon.isManaged)
    } else if (!open) {
      // Reset when dialog closes
      setHasBeenOpened(false)
    }
  }, [open, addon.isManaged, hasBeenOpened])

  // Close dialog when addon becomes managed (if it wasn't initially managed)
  useEffect(() => {
    // Only close if:
    // 1. Dialog is open
    // 2. We've already captured the initial state (hasBeenOpened)
    // 3. Addon is now managed
    // 4. It wasn't managed initially
    if (open && hasBeenOpened && addon.isManaged && !initiallyManaged) {
      onOpenChange(false)
    }
  }, [addon.isManaged, onOpenChange, open, initiallyManaged, hasBeenOpened])

  const getReadme = useCallback(async () => {
    const fallbackReadme = addon.description || 'No description provided'

    if (!addon.repo) {
      setReadme(fallbackReadme)
      return
    }

    const branch = addon.branch || 'main'

    const response = await fetch(
      `https://raw.githubusercontent.com/${addon.repo}/${branch}/README.md`
    )
    if (!response.ok) {
      setReadme(fallbackReadme)
      return
    }

    const text = await response.text()
    setReadme(text)
  }, [addon.repo, addon.branch, addon.description])

  const getMyRating = useCallback(async () => {
    if (!isAuthenticated) return
    apiClient
      .get(`/addon/${addon.name}/my-rating`)
      .then(async response => {
        if (response.status === 200) {
          const r = await response.json()
          setRating(r.data.rating)
        }
      })
      .catch(e => {
        console.error('Failed to fetch rating: ', e)
      })
  }, [addon.name, isAuthenticated])

  // Fetch readme when dialog opens
  useEffect(() => {
    if (!open) {
      return
    }
    getMyRating().catch(e => {
      console.error('Failed to fetch rating: ', e)
    })
    getReadme().catch(e => {
      console.error('Failed to fetch readme: ', e)
    })
  }, [open, getMyRating, getReadme])

  const rateAddon = async (newRating: number) => {
    if (rating === newRating) return

    const res = await apiClient.post(`/addon/${addon.name}/rate`, {
      is_like: newRating === 1,
    })

    if (res.status !== 200) {
      toast({
        title: 'Error',
        description: 'Failed to rate addon, try again later',
        icon: AlertTriangleIcon,
      })
      return
    }

    if (newRating === 1) {
      toast({
        title: 'Addon rated',
        description: `You liked ${addon.alias}`,
        icon: ThumbsUpIcon,
      })
    } else {
      toast({
        title: 'Addon rated',
        description: `You disliked ${addon.alias}`,
        icon: ThumbsDownIcon,
      })
    }

    setRating(newRating)
  }

  const handleReinstall = async () => {
    const [manifest, manifestError] = await safeCall<AddonManifest>(repoGetManifest(addon.name))

    if (manifestError || !manifest) {
      if (manifestError?.message.includes('no release found')) {
        toast({
          title: 'Error',
          description: 'No release found for this addon',
          icon: AlertTriangleIcon,
        })
      } else {
        toast({
          title: 'Error',
          description: 'Failed to fetch manifest during reinstall, try again later',
        })
      }
      return
    }

    const didInstall: boolean = await install(manifest, 'latest')
    if (!didInstall) return

    toast({
      title: 'Addon reinstalled',
      description: `${addon.alias} was reinstalled`,
      icon: CheckIcon,
    })

    setSelectedAddon(null)
    setIsDialogOpen(false)
  }

  const handleUninstall = async () => {
    const didUninstall = await uninstall(addon)
    if (!didUninstall) {
      toast({
        title: 'Error',
        description: 'Failed to uninstall addon, check log file for more information',
        icon: AlertTriangleIcon,
      })
      return
    }
    toast({
      title: 'Addon uninstalled',
      description: `${addon.alias} was uninstalled`,
      icon: CheckIcon,
    })

    setIsDialogOpen(false)
    setSelectedAddon(null)
  }

  const UnmanagedAddonNotice = () => {
    return (
      <div className="border rounded-lg p-4 bg-card mt-6">
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-muted-foreground">
            <PackageIcon className="w-4 h-4" />
            <p className="text-sm font-medium">
              This addon is not managed by Classic Addon Manager
            </p>
          </div>

          <Suspense
            fallback={
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <div className="w-3 h-3 rounded-full border-2 border-t-transparent border-current animate-spin"></div>
                <span>Checking repository...</span>
              </div>
            }
          >
            <AddonRepositoryMatch name={addon.name} />
          </Suspense>
        </div>
      </div>
    )
  }

  const RateAddonButtons = () => {
    if (!addon.isManaged) {
      return <div></div>
    }

    if (!isAuthenticated) {
      return (
        <Tooltip>
          <TooltipTrigger asChild>
            <span
              className="flex items-center gap-3 p-2 cursor-not-allowed opacity-50"
              aria-label="Log in to rate addons"
            >
              <ThumbsUpIcon className="w-5 h-5 text-muted-foreground" />
              <ThumbsDownIcon className="w-5 h-5 text-muted-foreground" />
            </span>
          </TooltipTrigger>
          <TooltipContent className="font-bold">Log in to rate addons</TooltipContent>
        </Tooltip>
      )
    }

    return (
      <div className="flex gap-2 items-center">
        <Button
          variant="ghost"
          size="icon"
          className={clsx(
            'h-8 w-9 transition-all duration-200 hover:bg-blue-100 dark:hover:bg-blue-900/30',
            rating === 1 && 'bg-blue-100 dark:bg-blue-900/30 border border-blue-500 text-blue-500'
          )}
          onClick={() => rateAddon(1)}
          aria-label="Like addon"
        >
          <ThumbsUpIcon
            className={clsx('w-5 h-5', {
              'text-blue-500': rating === 1,
              'text-muted-foreground': rating !== 1,
            })}
          />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          className={clsx(
            'h-8 w-9 transition-all duration-200 hover:bg-red-100 dark:hover:bg-red-900/30',
            rating === -1 && 'bg-red-100 dark:bg-red-900/30 border border-red-500 text-red-500'
          )}
          onClick={() => rateAddon(-1)}
          aria-label="Dislike addon"
        >
          <ThumbsDownIcon
            className={clsx('w-5 h-5', {
              'text-red-500': rating === -1,
              'text-muted-foreground': rating !== -1,
            })}
          />
        </Button>
      </div>
    )
  }

  return (
    <Dialog onOpenChange={onOpenChange} open={open}>
      <DialogContent className="max-w-0 min-w-[650px] md:max-w-[70svw] min-h-[500px] max-h-[90svh] lg:max-w-[850px] flex flex-col p-0">
        <DialogHeader className="p-6 pb-4 shrink-0 border-b">
          <DialogTitle className="text-2xl font-semibold mb-1">{addon.alias}</DialogTitle>

          {/* Display author and version information for managed addons */}
          {addon.isManaged && (
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm mb-3 text-muted-foreground">
              <span className="inline-flex items-center gap-1">
                <User className="w-3.5 h-3.5" />
                <span className="font-normal text-foreground/90">{addon.author}</span>
              </span>

              {addon.version ? (
                <Badge variant="secondary" className="inline-flex items-center gap-1">
                  <Tag className="w-3 h-3" />
                  {addon.version}
                </Badge>
              ) : (
                <Badge variant="outline">No Version</Badge>
              )}
            </div>
          )}

          {addon.isManaged && addon.description && (
            <DialogDescription className="text-sm text-muted-foreground">
              {addon.description}
            </DialogDescription>
          )}
        </DialogHeader>

        <div className="flex-1 overflow-y-auto px-6 pb-6 pt-2">
          {addon.isManaged && readme === 'loading' ? (
            <div className="flex flex-col items-center justify-center h-full text-center text-muted-foreground pt-10">
              <PackageIcon className="w-12 h-12 mb-4 opacity-50" />
              <p className="font-medium">Loading description...</p>
            </div>
          ) : (
            addon.isManaged && <RemoteAddonReadme readme={readme} />
          )}

          {/* Show notice if addon is not managed and is available in repository */}
          {!addon.isManaged && UnmanagedAddonNotice()}
        </div>

        <DialogFooter className="p-4 border-t">
          <div className="flex justify-between items-center w-full gap-4">
            {RateAddonButtons()}

            <div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2">
              {addon.isManaged && (
                <Button
                  type="button"
                  variant="outline"
                  className="flex items-center"
                  onClick={handleReinstall}
                >
                  <RefreshCw className="w-4 h-4" />
                  Reinstall
                </Button>
              )}
              <Button
                type="button"
                variant="destructive"
                className="flex items-center"
                onClick={handleUninstall}
              >
                <Trash2 className="w-4 h-4" />
                Uninstall
              </Button>
            </div>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
