// frontend/src/components/RemoteAddon.svelte
<script lang="ts">
  import {Blocks, Check, Download, Heart} from 'lucide-svelte'

    import {timeAgo} from "../utils";

    let {addon, isInstalled, onViewDetails}: {
        addon: AddonManifest,
        isInstalled: boolean,
        onViewDetails: () => void;
    } = $props();

    // We assume the icon exists and let the <img> `onerror` event tell us if it doesn't.
    let hasIcon = $state(true);
    let isNew = timeAgo(addon.added_at) < 32;

    const iconUrl = `https://raw.githubusercontent.com/${addon.repo}/${addon.branch}/icon.png`;

</script>

<div class="grid grid-cols-12 items-center gap-2 bg-muted/50 hover:bg-muted h-16 w-full rounded-lg cursor-pointer transition-colors px-3 py-2 group"
  onclick={onViewDetails}
>
    <!-- Left Section: Icon, Title, Stats-->
    <div class="flex items-center gap-3 col-span-5">
        <div class="relative flex-shrink-0">
            {#if hasIcon}
                <img class="h-10 w-10 rounded-md object-cover"
                     src={iconUrl}
                     alt="{addon.alias} icon"
                     loading="lazy"
                     onerror={() => hasIcon = false}
                />
            {:else}
                <!-- This block is now the fallback when the image fails to load -->
                <div class="flex items-center justify-center h-10 w-10 rounded-md bg-background border">
                    <Blocks class="h-5 w-5 opacity-40"/>
                </div>
            {/if}
            {#if isNew}
                <div class="absolute -top-1.5 -right-1.5 bg-red-500 text-white text-[8px] font-bold px-1 py-0.5 rounded-full shadow-md">
                    NEW
                </div>
            {/if}
        </div>
        <div class="flex flex-col overflow-hidden">
            <!-- First Row: Alias -->
            <div class="text-foreground font-medium truncate group-hover:text-primary transition-colors">{addon.alias}</div>
            <!-- Second Row: Stats (Downloads/Likes) -->
            <div class="flex items-center gap-3 text-xs text-muted-foreground mt-0.5">
                <div class="flex items-center gap-0.5" title="{addon.downloads} downloads">
                    <Download class="w-3 h-3"/> {addon.downloads}
                </div>
                {#if addon.like_percentage !== null}
                    <div class="flex items-center gap-0.5" title="{addon.like_percentage}% likes">
                        <Heart class="w-3 h-3"/> {addon.like_percentage}%
                    </div>
                {/if}
            </div>
        </div>
      {/if}
    </div>

    <!-- Middle Section 1: Author -->
    <div class="text-sm text-muted-foreground truncate text-center col-span-3" title="Author: {addon.author}">
        {addon.author}
    </div>
  </div>

    <!-- Middle Section 2: Tags -->
    {#if addon.tags.length > 0}
        <div class="flex items-center justify-end gap-1 flex-wrap col-span-3">
            {#each addon.tags.slice(0, 4) as tag}
                <span class="text-xs bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded whitespace-nowrap">{tag}</span>
            {/each}
            {#if addon.tags.length > 4}
                <span class="text-xs text-muted-foreground">+{addon.tags.length - 4} more</span>
            {/if}
        </div>
    {:else}
        <div class="col-span-3"></div>
    {/if}

    <!-- Right Section: Button -->
    <div class="flex justify-end col-span-1">
        {#if isInstalled}
            <Button
                    variant="ghost"
                    size="icon"
                    class="cursor-default text-green-500 focus-visible:ring-0 focus-visible:ring-offset-0"
                    disabled={true}
                    aria-label="Installed"
                    tabindex={-1}
            >
                <Check class="h-5 w-5"/>
            </Button>
        {:else}
            <Button
                    variant="ghost"
                    size="icon"
                    aria-label="View details and install"
                    class="text-muted-foreground hover:text-primary focus-visible:ring-primary/40"
            >
                <Download class="h-5 w-5"/>
            </Button>
        {/if}
    </div>
</div>

// frontend/src/components/addons/RemoteAddon.tsx
import { BlocksIcon, CheckIcon, DownloadIcon, HeartIcon } from 'lucide-react'
import { useState } from 'react'

import { daysAgo } from '@/lib/utils.ts'
import type { AddonManifest } from '@/lib/wails'

import { Button } from '../ui/button'

interface RemoteAddonProps {
  manifest: AddonManifest
  installed: boolean
}

export const RemoteAddon = ({ manifest, installed }: RemoteAddonProps) => {
  const [hasIcon, setIcon] = useState(true)

  const isNew = daysAgo(manifest.added_at) < 32
  const iconUrl = `https://raw.githubusercontent.com/${manifest.repo}/${manifest.branch}/icon.png`

  const Icon = () => {
    if (hasIcon) {
      return (
        <img
          className="h-10 w-10 rounded-md object-cover"
          src={iconUrl}
          alt={`${manifest.alias} icon`}
          loading="lazy"
          onError={() => setIcon(false)}
        />
      )
    }

    return (
      <div className="flex items-center justify-center h-10 w-10 rounded-md bg-background border">
        <BlocksIcon className="h-5 w-5 opacity-50 stroke-2" />
      </div>
    )
  }

  const NewBadge = () => {
    if (!isNew) return null
    return (
      <div className="absolute -top-1.5 -right-1.5 bg-red-500 text-white text-[8px] font-bold px-1 py-0.5 rounded-full shadow-md">
        NEW
      </div>
    )
  }

  const ActionButton = () => {
    if (installed) {
      return (
        <Button
          variant="ghost"
          size="icon"
          className="cursor-default text-green-500 focus-visible:ring-0 focus-visible:ring-offset-0"
          disabled={true}
          aria-label="Installed"
          tabIndex={-1}
        >
          <CheckIcon className="h-5 w-5" />
        </Button>
      )
    }

    return (
      <Button
        variant="ghost"
        size="icon"
        aria-label="View details and install"
        className="cursor-pointer text-muted-foreground hover:text-primary focus-visible:ring-primary/40"
      >
        <DownloadIcon className="h-5 w-5" />
      </Button>
    )
  }

  const Tags = () => {
    if (manifest.tags.length === 0) {
      return <div className="col-span-3"></div>
    }
    return (
      <div className="flex items-center justify-end gap-1 flex-wrap col-span-3">
        {manifest.tags.slice(0, 4).map(tag => (
          <>
            <span
              key={tag}
              className="text-xs bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded whitespace-nowrap"
            >
              {tag}
            </span>
            {manifest.tags.length > 4 && (
              <span className="text-xs text-muted-foreground">
                +{manifest.tags.length - 4} more
              </span>
            )}
          </>
        ))}
      </div>
    )
  }

  return (
    <div
      className="grid grid-cols-12 items-center gap-2 bg-muted/50 hover:bg-muted h-16 w-full rounded-lg cursor-pointer transition-colors px-3 py-2 group"
      onClick={() => alert('todo implement onclick')}
    >
      {/* Left Section: Icon, Title, Stats */}
      <div className="flex items-center gap-3 col-span-5">
        <div className="relative shrink-0">
          <Icon />
          <NewBadge />
        </div>
        <div className="flex flex-col  overflow-hidden">
          {/* First Row: Alias */}
          <div className="text-foreground font-medium truncate group-hover:text-primary transition-colors">
            {manifest.alias}
          </div>
          {/* Second Row: Stats (Downloads/Likes) */}
          <div className="flex items-center gap-3 text-xs text-muted-foreground mt-0.5">
            <div className="flex items-center gap-0.5" title={`${manifest.downloads} downloads`}>
              <DownloadIcon className="w-3 h-3" /> {manifest.downloads}
            </div>
            {manifest.like_percentage && (
              <div
                className="flex items-center gap-0.5"
                title={`${manifest.like_percentage}% likes`}
              >
                <HeartIcon className="w-3 h-3" /> {manifest.like_percentage}%
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Middle Section 1: Author */}
      <div
        className="text-sm text-muted-foreground truncate text-center col-span-3"
        title={`Author: ${manifest.author}`}
      >
        {manifest.author}
      </div>

      {/* Middle Section 2: Tags */}
      <Tags />

      {/* Right Section: Button */}
      <div className="flex justify-end col-span-1">
        <ActionButton />
      </div>
    </div>
  )
}
